insert into utente value("lauro.francesco47@gmail.com","Provadasa2#","Nicola","Siciliano","Sele45");
insert into utente value("lauro.francesco478@gmail.com","Provadasa2#","Matteo","Siciliano","Sele445");
insert into autore value("lauro.francesco1@gmail.com","Alpaca20#","Mario","Baldi","Font0");
insert into moderatore value("lauro.francesco137@gmail.com","Alpaca20#","Mario","Baldi","Font0","algo");
insert into articolo(Titolo,contenuto,categoria,stato,dataPubblicazione,id,scrittore,moderatore) value("Bubble Sort","dasdsadasdasdasdasdasdasdasdsadsadasdasdasdasdasdasdasdasdasdasdasdsadasdasdasdasd","algo","daPubblicare","2020-10-12",1,"lauro.francesco1@gmail.com","lauro.francesco137@gmail.com");
insert into articolo value("Ricerca binaria",2,"algo","dasdsadasdasdasdasdasdasdasdsadsadasdasdasdasdasdasdasdasdasdasdasdsadasdasdasdasd","pubblicato","2020-10-12","lauro.francesco1@gmail.com","lauro.francesco137@gmail.com");
insert into allegato value("file.psd",1);
insert into allegato value("fileCancella",1);
insert into commento value("bello",1,"lauro.francesco47@gmail.com");
INSERT INTO evento(data,via,città,nome,argomento,email) VALUES ('2020-10-12','Fontata','Pagani','Parliamo di ricorsione','ricorsione e robe varie','lauro.francesco1@gmail.com');
INSERT INTO evento(data,via,città,nome,argomento,email) VALUES ('2020-10-25','Umberto','Londra','Parliamo di cos','cose e robe varie','lauro.francesco1@gmail.com') ;
insert into messaggio(contenuto,id,mittente,destinatario,stato,data) value("we come va", 1, "lauro.francesco47@gmail.com", "lauro.francesco1@gmail.com", "inviato", "2020-01-19 08:40");
insert into risposta(contenuto,id,mittente,destinatario,stato,data) value("we tutto bene", 1,"lauro.francesco1@gmail.com", "lauro.francesco47@gmail.com","inviato", "2020-01-19 08:45");
insert into notifica (id,contenuto,stato,autore,moderatore) value(1,"pubblicazione articolo","inviato", "lauro.francesco1@gmail.com", "lauro.francesco137@gmail.com");
insert into notifica (id,contenuto,stato,autore,moderatore) value(2,"pubblicazione articolo","inviato", "lauro.francesco1@gmail.com", "lauro.francesco137@gmail.com");
insert into notifica (id,contenuto,stato,autore,moderatore) value(3,"Accettazione pubblicazione articolo","inviato", "lauro.francesco1@gmail.com", "lauro.francesco137@gmail.com");
insert into rating value(5,1,"lauro.francesco47@gmail.com");
insert into seguace value ("lauro.francesco47@gmail.com","lauro.francesco1@gmail.com");
insert into autore value("lauro.francesco1as12@gmail.com","Alpaca20#","Mario","Baldi","Font0");
insert into moderatore value("lauro7@gmail.com","Alpaca20#","Mario","Baldi","Font0","algo");
